### PR TITLE
Trying to add korean landing page.

### PR DESCRIPTION
**Pull request by mozodev**
Thanks.

### CODE REVIEW

**Comment by mozodev** [comment]
@mattl Could you let me know when to review and deploy these codes?

**Comment by soohyunpae** [comment]
@mattl could you review this asap? It's a local web site for the Summit notice and email subscription and we hope we can launch it very soon.

**Comment by mattl** [comment]
Assigned me. Gotta assign me or we miss stuff.

**Comment by soohyunpae** [comment]
@mattl Got it, thanks!

**Comment by soohyunpae** [comment]
@mattl Let me remind you that we're still waiting for your response!

**Comment by mattl** [comment]
So I've accepted this PR. We need to fix a few things, mostly around how bootstrap and jquery are loaded. We should load these from CDN instead of serving them locally. 

```
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script> 
```

**Pull request merged**
